spring:
  datasource:
      username: root
      password: lxlx
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.200.192.224:3306/safety?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.lx.pojo

server:
  port: 8888

