spring:
  datasource:
    # 配置多个数据源
    one:
      username: root
      password: lxlx
      jdbc-url: jdbc:mysql://101.200.192.224:3306/phone?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动
    two:
      username: root
      password: lxlx
      jdbc-url: jdbc:mysql://101.200.192.224:3306/zipkin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动

  redis:
    database: 0
    host: 101.200.192.224
    port: 6379
    timeout: 6000
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 5
        #连接池中的最小空闲连接
        min-idle: 0
    password: lxlx
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.lx.pojo

server:
  port: 8888
chaos:
  monkey:
    # 启动monkey
    enabled: true
    assaults:
      # 确定多少请求被攻击，1为攻击所有请求；5：每5个请求攻击一次 五分之一概率
      level: 5
      # 增加最小延时，毫秒
      latency-range-start: 1000
      # 增加最大延时，毫秒
      latency-range-end: 5000
      # 延时攻击启动
      latency-active: true
      # 异常攻击启动
      exceptions-active: true
      # kill应用启动
    #  kill-application-active: true
    watcher: # 控制范围
      controller: false
      rest-controller: false
      service: true
      repository: false # （JDBC和JPA）
      component: false
#otel:
#  # 导出器配置
#  exporter:
#    # 导出到Jaeger
##    jaeger:
##      enabled: false
##      endpoint: http://10.170.xx.xxx:xxxx
##      timeout: 10s
#    # 导出到日志
#    logging:
#      enabled: true
#  traces:
#    sampler:
#      # 采样频率
#      probability: 1.0
