spring:
  datasource:
      username: root
      password: lxlx
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.200.192.224:3306/phone?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.lx.pojo

server:
  port: 8888
chaos:
  monkey:
    # 启动monkey
    enabled: true
    assaults:
      # 确定多少请求被攻击，1为攻击所有请求；5：每5个请求攻击一次 五分之一概率
      level: 5
      # 增加最小延时，毫秒
      latency-range-start: 1000
      # 增加最大延时，毫秒
      latency-range-end: 5000
      # 延时攻击启动
      latency-active: true
      # 异常攻击启动
      exceptions-active: true
      # kill应用启动
    #  kill-application-active: true
    watcher: # 控制范围
      controller: false
      rest-controller: false
      service: true
      repository: false # （JDBC和JPA）
      component: false
#otel:
#  # 导出器配置
#  exporter:
#    # 导出到Jaeger
##    jaeger:
##      enabled: false
##      endpoint: http://10.170.xx.xxx:xxxx
##      timeout: 10s
#    # 导出到日志
#    logging:
#      enabled: true
#  traces:
#    sampler:
#      # 采样频率
#      probability: 1.0
